apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: go-app:latest # Replace with your image registry if needed
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: postgresql://postgres:password@postgres:5432/pgtest?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: go-app